### Requisição para a raiz da API
GET http://localhost:5122
### Requisição para a segunda funcionalidade da API
GET http://localhost:5122
### Requisição para a terceira funcionalidade da API
GET http://localhost:5122
